# Generated by Django 5.2.13 on 2026-05-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
