# Generated by Django 5.2.13 on 2026-05-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0002_userfile_is_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileshare',
            name='is_accessed',
            field=models.BooleanField(default=False),
        ),
    ]
