# Generated by Django 5.2.13 on 2026-05-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0003_fileshare_is_accessed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='userfile',
            unique_together={('user', 'file_hash')},
        ),
    ]
