# Generated by Django 5.2.13 on 2026-04-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0005_userfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
