# Generated by Django 5.2.13 on 2026-05-18 03:20

import fileapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0005_private_sharing_and_hash_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userfile',
            new_name='fileapp_use_user_id_570714_idx',
            old_name='fileapp_use_user_id_8a3f2d_idx',
        ),
        migrations.AlterField(
            model_name='fileversion',
            name='file',
            field=models.FileField(upload_to=fileapp.models.user_upload_path),
        ),
    ]
