# Generated by Django 5.2.13 on 2026-05-18 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0006_rename_fileapp_use_user_id_8a3f2d_idx_fileapp_use_user_id_570714_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateshare',
            name='parent_share',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_shares', to='fileapp.privateshare'),
        ),
    ]
