# Generated by Django 5.2.13 on 2026-04-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0006_userfile_deleted_at_userfile_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='file_hash',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
