# Generated by Django 5.2.13 on 2026-05-21 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0007_privateshare_parent_share'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateshare',
            name='inactivity_revoke_days',
        ),
    ]
