# Generated by Django 5.2.13 on 2026-04-28 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0008_fileshare'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fileshare',
            new_name='fileapp_fil_token_24f799_idx',
            old_name='fileapp_fil_token_2d9fd2_idx',
        ),
        migrations.RenameIndex(
            model_name='fileshare',
            new_name='fileapp_fil_owner_i_6c7921_idx',
            old_name='fileapp_fil_owner_i_5b1a1b_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
