# Generated by Django 5.2.13 on 2026-04-29 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0009_rename_fileapp_fil_token_2d9fd2_idx_fileapp_fil_token_24f799_idx_and_more'),
        ('fileapp', '0009_user_auth_provider'),
    ]

    operations = [
    ]
