# Generated by Django 5.2.13 on 2026-05-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0010_merge_20260429_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileshare',
            name='is_revoked',
            field=models.BooleanField(default=False),
        ),
    ]
