# Generated by Django 4.2.30 on 2026-05-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0010_spacepresence'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacefile',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spacefile',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
