# Generated by Django 4.2.30 on 2026-05-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0011_spacefile_is_pinned_spacefile_pinned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacemember',
            name='mute_in_app',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spacemember',
            name='mute_weekly_digest',
            field=models.BooleanField(default=False),
        ),
    ]
