# Generated by Django 6.0.4 on 2026-05-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0012_spacemember_mute_in_app_and_more'),
    ]

    operations = [
        migrations.DeleteModel(name='Space'),
        migrations.DeleteModel(name='SpaceFile'),
        migrations.DeleteModel(name='SpaceFileVersion'),
        migrations.DeleteModel(name='SpaceMember'),
        migrations.DeleteModel(name='SpaceNotification'),
        migrations.DeleteModel(name='SpacePresence'),
        migrations.DeleteModel(name='SpaceTask'),
        migrations.DeleteModel(name='SpaceThread'),
        migrations.DeleteModel(name='SpaceThreadComment'),
    ]